apiVersion: v1
kind: ConfigMap
metadata:
  name: jdbc-demo
  labels:
    app: jdbc-demo
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${MYSQL_ROOT_PASSWORD}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"
